### ISSUE TITLE
60 RPC per minute limit exceeded error (cache?)

### ISSUE THREAD

**Issue by The-Collective** [tmtowtdi/MontyLacuna#10]
When running excav report and have it once run into RPC limit error, then rerunning it after gives the error over and over - no matter that nothing else is eating RPCs at the time.

Then it errors out if left running.

Error Report: http://pastebin.com/f5Z3GUWd

Edit: now it is happening on spy report as well. (All other scripts seem fine)

**Comment by The-Collective** [comment]
Once rerun after some time (and the Cache has been cleared automatically), seems fine

**Comment by tmtowtdi** [comment]
Those REQ log entries you're seeing don't post the time to the screen, but they do write the timestamp into the log file.  

Check inside var/us1.log and look for those "WARNING" entries.  When you see an entry that says "sleeping for one minute", the next log entry's timestamp should be one minute later -- is that what you're seeing?

Either way, I've just updated the code to automatically turn off all caching when it hits that 60 RPC/min limit before it re-tries the request.  I'm checking on a reasonable way to test that now.

**Comment by The-Collective** [comment]
woot!
